os: linux
language: node_js
dist: xenial
node_js:
  - 12
cache:
  directories:
    - "node_modules"
  npm: true
services:
  - mongodb
  - docker
addons:
  apt:
    packages:
      - docker-ce
before_install:
  - docker-compose build
script: npm run test
deploy:
  app: auth-services-aden
  provider: heroku
  api_key: $HEROKU_API
    