sudo: required
node_js:
  - 10
services:
  - mongodb
  - docker
cache:
  directories:
    - "node_modules"
  yarn: true
addons:
  apt:
    packages:
      - docker-ce
script:
  - docker-compose -f docker-compose.env.yml up
