os: linux

language: node_js

dist: xenial

node_js:
  - 12

cache:
  directories:
    - "node_modules"
  npm: true

stages:
  - name: lint
    if: type = pull_request
  - name: deploy
    if: type = push
  - name: test
    if: branch != master

jobs:
  include:
    - stage: lint
      allow_failures:
        - if: branch != develop
      script: npm run lint
    - stage: test
      script: npm run test
    - stage: deploy
      services:
        - mongodb
        - docker
      addons:
        apt:
          packages:
            - docker-ce
      script: npm run test
      deploy:
          provider: heroku
          api_key: $HEROKU_API
          app: auth-services-aden

