language: bash
sudo: required
services:
  - mongodb
  - docker
before_install:
  - sudo apt-get install mongodb-clients
  - sleep 15
  - docker build -t aghora/auth-service .
script:
  - docker run -e CI=true aghora/auth-service npm run test
