language: bash
sudo: required
services:
  - docker

before_install:
  - docker build -t aghora/auth-service .

script:
  - docker run -e CI=true TRAVIS_SECURE_ENV_VARS=true aghora/auth-service npm run test
