language: bash
sudo: required
services:
  - docker
  - mongodb
before_install:
  - sudo apt-get install mongodb-clients
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
  - docker build -t aghora/auth-service .
script:
  - docker run -e CI=true aghora/auth-service npm run test
