os: linux
language: node_js
dist: xenial
node_js:
  - 10
services:
  - mongodb
  - docker
cache:
  directories:
    - "node_modules"
  npm: true
addons:
  apt:
    packages:
      - docker-ce
before_install:
  - sudo systemctl status mongod
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
  - docker build -t aghora/auth-service .
script:
  - docker run -e TOKEN_SECRET=$TOKEN_SECRET -e PORT=$PORT -e MONGO_URI=$MONGO_URI aghora/auth-service npm run test
# env:
#   global:
#     - TOKEN_SECRET=QWERTY2#4 PORT=3005
