sudo: required
node_js:
  - 10
services:
  - mongodb
  - docker
cache:
  directories:
    - "node_modules"
before_install:
  - sudo apt-get install mongodb-clients
  - sudo systemctl status mongod
  - docker build -t aghora/auth-service .
script:
  - docker run -e CI=true aghora/auth-service npm run test
