os: linux
language: node_js
dist: xenial
node_js:
  - 12
cache:
  directories:
    - "node_modules"
  npm: true
jobs:
  include:
    - stage: lint
      script:
        - npm run lint
    - stage: test
      script:
       - npm run test -- --exit
    # - stage: deploy
    #   script:
    #     - services:
    #       - mongodb
    #       - docker
    #     - addons:
    #       apt:
    #         packages:
    #           - docker-ce
    #     - npm run test -- --exit
    #   - deploy:
    #       provider: heroku
    #       api_key: $HEROKU_API
    #       app: auth-services-aden
    #       on:
    #         branch: master
stages:
  - name: test
    if: type = pull_request
  - name: lint
    if: type = pull_request AND branch != master
  # - name: deploy
  #   if: type = push AND branch = master

