language: bash
sudo: required
services:
  - docker

before_install:
  - docker build -t aghora/auth-service .
services: 
  - mongodb
script:
  - docker run -e CI=true aghora/auth-service npm run test
