sudo: required
node_js:
  - 10
services:
  - docker
cache:
  directories:
    - "node_modules"
  yarn: true
addons:
  apt:
    packages:
      - docker-ce
before_script:
  - docker-compose -f docker-compose.env.yml build --parallel
script:
  - docker-compose -f docker-compose.env.yml up
