os: linux
language: node_js
dist: xenial
node_js:
  - 10
services:
  - mongodb
  - docker
cache:
  directories:
    - "node_modules"
  npm: true
addons:
  apt:
    packages:
      - docker-ce
before_install:
  - sudo systemctl status mongod
  - docker-compose -f docker-compose.dev.yml build
script: npm run test
