os: linux
language: node_js
dist: xenial
node_js:
  - 12
cache:
  directories:
    - "node_modules"
  npm: true
services:
  - mongodb
  - docker
addons:
  apt:
    packages:
      - docker-ce
jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: deploy
      script: npm run test
      deploy:
          provider: heroku
          api_key: $HEROKU_API
          app: auth-services-aden
stages:
  - name: lint
    if: type = pull_request
  - name: deploy
    if: branch = master

