language: bash
sudo: required
services:
  - docker
  - mongodb
before_install:
  - docker build -t aghora/auth-service .
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]})'
script:
  - docker run -e CI=true aghora/auth-service npm run test
