sudo: required
node_js:
  - 10
services:
  - docker
  - mongo
cache:
  directories:
    - "node_modules"
  yarn: true
addons:
  apt:
    packages:
      - docker-ce
before_install:
  - docker build -t aghora/auth-service .
script:
  - docker run aghora/auth-service npm run test
# env:
#   - TOKEN_SECRET=$TOKEN_SECRET
#   - BACK_URI=mongo
