version: "3"
services:
  # db:
  # image: "mongo"
  # restart: always
  # container_name: "mongo"
  # ports:
  #   - 27017:27017
  # logging:
  #   driver: "none"
  authservice:
    build: .
    ports:
      - 8080:3005
    volumes:
      - "/home/authService/node_modules"
      - ".:/home/authService"
    # links:
    #   - db
    environment:
      - NODE_ENV=development
      - PORT=$PORT
      - TOKEN_SECRET=$TOKEN_SECRET
      - MONGO_URI=$DOCKER_URI
    # env_file: .env.prod
