version: "3"
services:
  db:
    image: "mongo"
    restart: always
    container_name: "authServiceMongo"
    env_file: .env.prod
  authservice:
    build: .
    ports:
      - 8080:3006
    volumes:
      - "/home/authService/node_modules"
      - ".:/home/authService"
    environment:
      - NODE_ENV=production
    env_file: .env.prod
