version: "3"
services:
  db:
    image: "mongo"
    restart: always
    container_name: "authServiceMongo"
    env_file: .env
  authservice:
    build: .
    ports:
      - 8080:3005
    volumes:
      - "/home/authService/node_modules"
      - ".:/home/authService"
    command: 
    env_file: .env
