version: "3"
services:
  db:
    image: "mongo"
    restart: always
    container_name: "mydb_test"
    ports:
      - 27017:27017
    logging:
      driver: "none"
    volumes:
      - /home/docker/mongod:/var/lib/mongod
  auth-test:
    build: .
    ports:
      - 8080:3005
    volumes:
      - /home/authService/node_modules
      - .:/home/authService
    links:
      - db
    environment:
      - NODE_ENV=development
      - PORT=$PORT
      - TOKEN_SECRET=$TOKEN_SECRET
      - MONGO_URI=$MONGO_URI
    command:
      - "true"
      - npm run test -- --exit
